// 全部界面文案集中在此
export const t = {
  appName: 'GitGod',
  openRepo: '打开仓库',
  openRepoHint: '选择一个 Git 仓库的文件夹开始',
  recent: '最近打开',
  newTab: '打开仓库（新页签）',
  closeTab: '关闭页签',
  loadingHistory: '正在加载完整历史…',
  commits: (n: number) => `${n.toLocaleString('zh-CN')} 个提交`,
  filter: '筛选分支、标签…',
  branches: '本地分支',
  remotes: '远程分支',
  tags: '标签',
  stashes: '贮藏',
  worktrees: '工作树',
  detached: '游离 HEAD',
  colSubject: '说明',
  colAuthor: '作者',
  colDate: '日期',
  colCommit: '提交',
  noSelection: '选择一个提交查看详情',
  author: '作者',
  committer: '提交者',
  parents: '父提交',
  files: (n: number) => `改动文件（${n}）`,
  history: '全部提交',
  changes: '本地更改',
  unstaged: '未暂存',
  staged: '已暂存',
  stageAll: '全部暂存',
  unstageAll: '全部取消',
  stageFile: '暂存',
  unstageFile: '取消暂存',
  stageHunk: '暂存区块',
  unstageHunk: '取消暂存区块',
  stageLines: (n: number) => `暂存所选 ${n} 行`,
  unstageLines: (n: number) => `取消暂存所选 ${n} 行`,
  commitPlaceholder: '提交信息（Ctrl+Enter 提交）',
  commit: '提交',
  amend: '修补上次提交',
  clean: '工作区是干净的',
  pickFile: '选择一个文件查看改动',
  binary: '二进制文件，无法显示改动',
  tooLarge: '改动过大，无法显示',
  noDiff: '没有文本改动',
  truncated: (n: number) => `只显示前 ${n} 行`,
  back: '返回提交信息',
  noCommits: '这个仓库还没有提交',
  status: { A: '新增', M: '修改', D: '删除', R: '重命名', C: '复制', T: '类型变更', '?': '未跟踪', U: '冲突' } as Record<string, string>,
}

export function fmtTime(sec: number): string {
  const d = new Date(sec * 1000)
  const p = (n: number) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`
}
