// 全部界面文案集中在此
export const t = {
  appName: 'GitGod',
  openRepo: '打开仓库',
  openRepoHint: '选择一个 Git 仓库的文件夹开始',
  recent: '最近打开',
  newTab: '打开仓库（新页签）',
  closeTab: '关闭页签',
  loadingHistory: '正在加载完整历史…',
  commits: (n: number) => `${n.toLocaleString('zh-CN')} 个提交`,
  filter: '筛选分支、标签…',
  branches: '本地分支',
  remotes: '远程分支',
  tags: '标签',
  stashes: '贮藏',
  worktrees: '工作树',
  detached: '游离 HEAD',
  colSubject: '说明',
  colAuthor: '作者',
  colDate: '日期',
  colCommit: '提交',
  noSelection: '选择一个提交查看详情',
  author: '作者',
  committer: '提交者',
  parents: '父提交',
  files: (n: number) => `改动文件（${n}）`,
  history: '全部提交',
  changes: '本地更改',
  unstaged: '未暂存',
  staged: '已暂存',
  stageAll: '全部暂存',
  unstageAll: '全部取消',
  stageFile: '暂存',
  unstageFile: '取消暂存',
  stageHunk: '暂存区块',
  unstageHunk: '取消暂存区块',
  stageLines: (n: number) => `暂存所选 ${n} 行`,
  unstageLines: (n: number) => `取消暂存所选 ${n} 行`,
  commitPlaceholder: '提交信息（Ctrl+Enter 提交）',
  commit: '提交',
  amend: '修补上次提交',
  clean: '工作区是干净的',
  pickFile: '选择一个文件查看改动',
  binary: '二进制文件，无法显示改动',
  tooLarge: '改动过大，无法显示',
  noDiff: '没有文本改动',
  truncated: (n: number) => `只显示前 ${n} 行`,
  back: '返回提交信息',
  ok: '确定',
  cancel: '取消',
  fetch: '获取',
  pull: '拉取',
  push: '推送',
  stash: '贮藏',
  newBranch: '新建分支',
  log: '命令日志',
  logEmpty: '还没有执行过命令',
  working: '正在执行…',
  inProgress: {
    merge: '合并进行中',
    rebase: '变基进行中',
    'cherry-pick': 'Cherry-pick 进行中',
    revert: '撤销提交进行中',
  } as Record<string, string>,
  inProgressHint: '解决冲突并暂存后点「继续」',
  continue: '继续',
  abort: '中止',
  checkout: '检出',
  checkoutCommit: '检出此提交',
  checkoutRemote: '检出为本地分支',
  mergeInto: (b: string) => `合并到 ${b}`,
  rebaseOnto: (b: string) => `把 ${b} 变基到这里`,
  pushBranch: '推送…',
  rename: '重命名…',
  delete: '删除…',
  deleteTag: '删除标签…',
  newBranchHere: '在此新建分支…',
  newTagHere: '在此新建标签…',
  cherryPick: 'Cherry-pick 到当前分支',
  revertCommit: '撤销此提交（生成反向提交）',
  resetTo: (b: string) => `把 ${b} 重置到这里…`,
  copyId: '复制提交 ID',
  stashApply: '应用',
  stashPop: '应用并删除',
  stashDrop: '删除…',
  branchName: '分支名',
  tagName: '标签名',
  tagMessage: '说明（留空则创建轻量标签）',
  checkoutAfterCreate: '创建后检出',
  newName: '新名称',
  deleteBranchTitle: (b: string) => `删除分支 ${b}`,
  forceDelete: '强制删除（丢弃未合并的提交）',
  deleteTagTitle: (n: string) => `删除标签 ${n}`,
  dropStashTitle: '删除贮藏',
  dropStashWarning: '贮藏里的改动将无法恢复。',
  resetTitle: (b: string) => `重置 ${b}`,
  resetMode: '重置方式',
  resetSoft: '软重置：保留改动，并保持已暂存',
  resetMixed: '混合重置：保留改动，取消暂存',
  resetHard: '硬重置：丢弃工作区和暂存区的全部改动',
  resetHardWarning: '硬重置会丢弃未提交的改动，无法恢复。',
  stashTitle: '贮藏本地更改',
  stashMessage: '说明',
  includeUntracked: '包含未跟踪的文件',
  pushTitle: (b: string) => `推送 ${b}`,
  pushTo: (r: string) => `推送到 ${r}`,
  pushNew: (r: string) => `远程还没有这个分支，将创建 ${r} 并设为上游。`,
  pushMismatch: (local: string, up: string) => `本地分支 ${local} 的上游是 ${up}，名字不一致。请确认要推送到哪里。`,
  pushTarget: '推送目标',
  pushToUpstream: (up: string) => `推送到上游 ${up}`,
  pushToSameName: (r: string) => `推送到同名分支 ${r}，并改为上游`,
  remote: '远程',
  forcePush: '强制推送（--force-with-lease）',
  noRemote: '这个仓库没有配置远程',
  noBranch: '当前不在任何分支上',
  noCommits: '这个仓库还没有提交',
  status: { A: '新增', M: '修改', D: '删除', R: '重命名', C: '复制', T: '类型变更', '?': '未跟踪', U: '冲突' } as Record<string, string>,
}

export function fmtTime(sec: number): string {
  const d = new Date(sec * 1000)
  const p = (n: number) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`
}
